
server:
  servlet:
    context-path: /vstore
  port: 8003

spring:
  profiles:
    active: jdbc
  security:
#    user:
#      name: username
#      password: user
#      roles: ADMIN,USER
    authorities-by-username-query:
      SELECT  distinct u.login_name AS username , p.permission_code AS authority
      FROM     sys_user u
      JOIN  sys_user_role ur		ON ur.user_id = u.id
      JOIN  sys_role r				ON ur.role_id = r.id
      JOIN  sys_role_permission rp ON rp.role_id = r.id
      JOIN  sys_permission p		ON rp.permission_id = p.id
      WHERE   p.permission_code is not null  and u.login_name = ?
    users-by-username-query:
      SELECT login_name AS username,password,state as enabled FROM  sys_user WHERE login_name =?
    load-all-resource-query:
      select permission_code code,resource_url as  urls  from  sys_permission p
      left join sys_permission_resource pr on p.id=pr.permission_id
      left join sys_resource  r  on r.id=pr.resource_id
      where resource_url is not null





#dubbo:
#  scan:
#    base-packages: com.vstore.controller
#  registry:
#    timeout: 60000
#    address: zookeeper://192.168.56.228:2181
#  protocol:
#    name: dubbo
#    port: 20880
#  consumer:
#    check: false
#  application:
#    name: vstore
